### ISSUE TITLE
Add Configurable CORS Support with Allowed Origins

### ISSUE THREAD

**Issue by bharatnpti** [eclipse-lmos/lmos-runtime#36]
Implement Cross-Origin Resource Sharing (CORS) functionality with configurable options to specify allowed origins, methods, headers, and URL patterns.

This enhancement will support a range of frontend integrations, while ensuring robust security through configurable cross-origin access policies.

**Comment by kaikreuzer** [comment]
Implemented through https://github.com/lmos-ai/lmos-runtime/pull/71
